### ISSUE TITLE
💡 [REQUEST] - remove `console.debug` react-ipynb-renderer is working

### ISSUE THREAD

**Issue by KJSanchez** [righ/react-ipynb-renderer#51]
### Summary

I'm trying to declutter the output from jest as much as possible, mostly from failed prop-type checks.

This call to `console.debug` is one of those things that clutters my workflow. What's the best way to disable it? 

### Basic Example

_

### Drawbacks

_

**Comment by righ** [comment]
Removed debug output in v.2.2.2.
Please check if it is as expected.

**Comment by righ** [comment]
@KJSanchez Did it work as expected?
If it works fine, please close the Issue.
